# Generated by Django 6.0.4 on 2026-04-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='actual_issues',
            field=models.ManyToManyField(blank=True, related_name='actual_requests_multi', to='services.issuecatalog'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reported_issues',
            field=models.ManyToManyField(blank=True, related_name='reported_requests_multi', to='services.issuecatalog'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reported_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_requests', to='services.issuecatalog'),
        ),
    ]
