# Generated by Django 6.0.4 on 2026-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_actual_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('diagnosed', 'Diagnosed'), ('quote_pending', 'Quote Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_cash', 'Pending Cash Collection')], default='pending', max_length=20),
        ),
    ]
