# Generated by Django 5.2.6 on 2026-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('diagnosed', 'Diagnosed'), ('quote_pending', 'Quote Pending'), ('in_progress', 'In Progress'), ('pending_payment', 'Pending Payment'), ('pending_cash', 'Pending Cash Collection'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
