# Generated by Django 6.0.4 on 2026-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('CASH', 'Cash')], default='ONLINE', max_length=10),
        ),
    ]
